name: Zad4 - Simple txt artifact

on:
 workflow_dispatch: # MANUAL TRIGGER

jobs:
  create-file:

    runs-on: ubuntu-latest

    steps:
    - name: Create a file
      run:  echo $(date) > current_date.txt
    - name: Store data as variable
      run: echo "DATE=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

    - name: Create additional log file
      run: |
       echo "=====  LOG FILE =====" > log.info.txt
       echo "Workflow starts $(date)" >> log.info.txt
       echo "DATE = $DATE" >> log.info.txt
       echo "current.data.txt created and saved as artifact." >> log.info.txt
       cat log_info.txt
      
    - name: Archive File as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: current_date_artifact_${{ env.DATE }}
        path: current_date.txt

    - name: Upload log artifact
      uses: actions/upload-artifact@v4
      with:
       name: log_artifact_${{ env.DATE }}
       path: log_info.txt
