# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Zad1 - manual job

on:
 workflow_dispatch: # MANUAL TRIGGER

jobs:
  display-env-info:

    runs-on: ubuntu-latest

    steps:
    - name: Print system name on console
      run: |
        echo "Running job on:"
        echo ${{ runner.os }}
